{
 "title": "SAN Storage",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "backend",
    "label": "Storage",
    "query": "label_values(san_storage_info, backend_name)"
   },
   {
    "name": "pool",
    "label": "Pool",
    "query": "label_values(san_pool_total_capacity_mib{backend_name=~\"$backend\"},pool_name)"
   },
   {
    "name": "node",
    "label": "Controller node",
    "query": "label_values(san_cpu_total{backend_name=~\"$backend\",cpu=~\"0\",mode=~\"idlePct\"},node)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total controllers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "san_totalNodes{backend_name=~\"$backend\"}"
    }
   ]
  },
  {
   "title": "Total capacity",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "san_totalCapacityMiB{backend_name=~\"$backend\"}"
    }
   ]
  },
  {
   "title": "Allocated",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "san_allocatedCapacityMiB{backend_name=~\"$backend\"}"
    }
   ]
  },
  {
   "title": "Free",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "san_freeCapacityMiB{backend_name=~\"$backend\"}"
    }
   ]
  },
  {
   "title": "Cluster controllers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "san_clusterNodes{backend_name=~\"$backend\"}"
    }
   ]
  },
  {
   "title": "Online controllers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "san_onlineNodes{backend_name=~\"$backend\"}"
    }
   ]
  },
  {
   "title": "CPU Busy - Node $node",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "repeat": "node",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(((count(count(san_cpu_total{backend_name=~\"$backend\",node=~\"$node\"}) by (cpu))) - avg(sum by (mode)(irate(san_cpu_total{mode='idlePct',backend_name=~\"$backend\",node=~\"$node\"}[15m])))) * 100) / count(count(san_cpu_total{backend_name=~\"$backend\",node=~\"$node\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU Busy - Node $node",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(((count(count(san_cpu_total{backend_name=~\"$backend\",node=~\"$node\"}) by (cpu))) - avg(sum by (mode)(irate(san_cpu_total{mode='idlePct',backend_name=~\"$backend\",node=~\"$node\"}[15m])))) * 100) / count(count(san_cpu_total{backend_name=~\"$backend\",node=~\"$node\"}) by (cpu))"
    }
   ]
  },
  { "title": "Pool Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Pool capacity - $pool",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 14 },
   "repeat": "pool",
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "san_pool_total_capacity_mib{backend_name=~\"$backend\",pool_name=~\"$pool\"}"
    }
   ]
  },
  {
   "title": "Pool free - $pool",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 14 },
   "repeat": "pool",
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "san_pool_free_capacity_mib{backend_name=~\"$backend\",pool_name=~\"$pool\"}"
    }
   ]
  },
  {
   "title": "Total vLUN - $pool",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 14 },
   "repeat": "pool",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "san_pool_totalLUNs{backend_name=~\"$backend\",pool_name=~\"$pool\"}"
    }
   ]
  },
  {
   "title": "Pool capacity - $pool",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 18 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "san_pool_total_capacity_mib{backend_name=~\"$backend\",pool_name=~\"$pool\"}"
    }
   ]
  },
  {
   "title": "Pool free - $pool",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 18 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "san_pool_free_capacity_mib{backend_name=~\"$backend\",pool_name=~\"$pool\"}"
    }
   ]
  },
  {
   "title": "Total vLUN - $pool",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "san_pool_totalLUNs{backend_name=~\"$backend\",pool_name=~\"$pool\"}"
    }
   ]
  },
  {
   "title": "Pool capacity - $pool",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 22 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "san_pool_total_capacity_mib{backend_name=~\"$backend\",pool_name=~\"$pool\"}"
    }
   ]
  },
  {
   "title": "Pool free - $pool",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 22 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "san_pool_free_capacity_mib{backend_name=~\"$backend\",pool_name=~\"$pool\"}"
    }
   ]
  },
  {
   "title": "Total vLUN - $pool",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "san_pool_totalLUNs{backend_name=~\"$backend\",pool_name=~\"$pool\"}"
    }
   ]
  },
  {
   "title": "Pool capacity - $pool",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 26 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "san_pool_total_capacity_mib{backend_name=~\"$backend\",pool_name=~\"$pool\"}"
    }
   ]
  },
  {
   "title": "Pool free - $pool",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 26 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "san_pool_free_capacity_mib{backend_name=~\"$backend\",pool_name=~\"$pool\"}"
    }
   ]
  },
  {
   "title": "Total vLUN - $pool",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "san_pool_totalLUNs{backend_name=~\"$backend\",pool_name=~\"$pool\"}"
    }
   ]
  },
  {
   "title": "Pool capacity - $pool",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 30 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "san_pool_total_capacity_mib{backend_name=~\"$backend\",pool_name=~\"$pool\"}"
    }
   ]
  },
  {
   "title": "Pool free - $pool",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 30 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "san_pool_free_capacity_mib{backend_name=~\"$backend\",pool_name=~\"$pool\"}"
    }
   ]
  },
  {
   "title": "Total vLUN - $pool",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "san_pool_totalLUNs{backend_name=~\"$backend\",pool_name=~\"$pool\"}"
    }
   ]
  },
  { "title": "Pool Statistic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "IO's per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "san_pool_number_read_io{backend_name=\"$backend\"}",
     "legendFormat": "Read IO - {{pool_name}}"
    },
    {
     "expr": "san_pool_number_write_io{backend_name=\"$backend\"}",
     "legendFormat": "Write IO - {{pool_name}}"
    },
    {
     "expr": "san_pool_number_read_io{backend_name=\"$backend\"} + san_pool_number_write_io{backend_name=\"$backend\"}",
     "legendFormat": "Total IO - {{pool_name}}"
    }
   ]
  },
  {
   "title": "Throughput  per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "san_pool_read_kb{backend_name=\"$backend\"}",
     "legendFormat": "Read - {{pool_name}}"
    },
    {
     "expr": "san_pool_write_kb{backend_name=\"$backend\"}",
     "legendFormat": "Write - {{pool_name}}"
    },
    {
     "expr": "san_pool_read_kb{backend_name=\"$backend\"} + san_pool_write_kb{backend_name=\"$backend\"}",
     "legendFormat": "Total - {{pool_name}}"
    }
   ]
  },
  {
   "title": "IO's size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "san_pool_read_IOSize_kb{backend_name=\"$backend\"}",
     "legendFormat": "Read IO's size - {{pool_name}}"
    },
    {
     "expr": "san_pool_write_IOSize_kb{backend_name=\"$backend\"}",
     "legendFormat": "Write IO's size - {{pool_name}}"
    }
   ]
  },
  {
   "title": "Service time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "san_pool_read_service_time_ms{backend_name=\"$backend\"}",
     "legendFormat": "Read service time - {{pool_name}}"
    },
    {
     "expr": "san_pool_write_service_time_ms{backend_name=\"$backend\"}",
     "legendFormat": "Write service time - {{pool_name}}"
    }
   ]
  },
  {
   "title": "Queue length",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "san_pool_queue_length{backend_name=\"$backend\"}",
     "legendFormat": "Queue length - {{pool_name}}"
    }
   ]
  },
  { "title": "Port", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Read IO's per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "san_port_number_read_io{backend_name=\"$backend\"}",
     "legendFormat": "Node-{{node}} Card-{{card}} Slot-{{slot}}"
    }
   ]
  },
  {
   "title": "Write IO's per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "san_port_number_write_io{backend_name=\"$backend\"}",
     "legendFormat": "Node-{{node}} Card-{{card}} Slot-{{slot}}"
    }
   ]
  },
  {
   "title": "Read throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "san_port_read_kb{backend_name=\"$backend\"}",
     "legendFormat": "Node-{{node}} Card-{{card}} Slot-{{slot}}"
    }
   ]
  },
  {
   "title": "Write  throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "san_port_write_kb{backend_name=\"$backend\"}",
     "legendFormat": "Node-{{node}} Card-{{card}} Slot-{{slot}}"
    }
   ]
  },
  {
   "title": "Read service time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "san_port_read_service_time_ms{backend_name=\"$backend\"}",
     "legendFormat": "Node-{{node}} Card-{{card}} Slot-{{slot}}"
    }
   ]
  },
  {
   "title": "Write service time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "san_port_write_service_time_ms{backend_name=\"$backend\"}",
     "legendFormat": "Node-{{node}} Card-{{card}} Slot-{{slot}}"
    }
   ]
  }
 ]
}